server:
  port: 8080
spring:
  redis:
    host: xxx
    port: 6688
    database: 0
    password: xxx
    timeout: 3000
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: 5000