server:
  port: 8080
spring:
  redis:
    host: redis_ip
    port: 6739
    database: 0
    password: redis_password
    timeout: 3000
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: 5000